spring:
  application:
    name: recat
  datasource:
    url: ${db_url}
    username: ${db_user}
    password: ${db_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    open-in-view: false
logging.level:
  org.springframework.security: TRACE
server:
  error:
    include-message: always






 